# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
